namespace DungeonMastersGuide.Chapter1
{
    public static class FormsOfGovernment
    {
        public static List<FormOfGovernment> Governments = new();

        static FormsOfGovernment()
        {
            Governments.Add(new FormOfGovernment(0, string.Empty));
            Governments.Add(new FormOfGovernment(1, "Autocracy"));
            Governments.Add(new FormOfGovernment(2, "Autocracy"));
            Governments.Add(new FormOfGovernment(3, "Autocracy"));
            Governments.Add(new FormOfGovernment(4, "Autocracy"));
            Governments.Add(new FormOfGovernment(5, "Autocracy"));
            Governments.Add(new FormOfGovernment(6, "Autocracy"));
            Governments.Add(new FormOfGovernment(7, "Autocracy"));
            Governments.Add(new FormOfGovernment(8, "Autocracy"));
            Governments.Add(new FormOfGovernment(9, "Bureaucracy"));
            Governments.Add(new FormOfGovernment(10, "Bureaucracy"));
            Governments.Add(new FormOfGovernment(11, "Bureaucracy"));
            Governments.Add(new FormOfGovernment(12, "Bureaucracy"));
            Governments.Add(new FormOfGovernment(13, "Bureaucracy"));
            Governments.Add(new FormOfGovernment(14, "Confederacy"));
            Governments.Add(new FormOfGovernment(15, "Confederacy"));
            Governments.Add(new FormOfGovernment(16, "Confederacy"));
            Governments.Add(new FormOfGovernment(17, "Confederacy"));
            Governments.Add(new FormOfGovernment(18, "Confederacy"));
            Governments.Add(new FormOfGovernment(19, "Confederacy"));
            Governments.Add(new FormOfGovernment(20, "Democracy"));
            Governments.Add(new FormOfGovernment(21, "Democracy"));
            Governments.Add(new FormOfGovernment(22, "Democracy"));
            Governments.Add(new FormOfGovernment(23, "Dictatorship"));
            Governments.Add(new FormOfGovernment(24, "Dictatorship"));
            Governments.Add(new FormOfGovernment(25, "Dictatorship"));
            Governments.Add(new FormOfGovernment(26, "Dictatorship"));
            Governments.Add(new FormOfGovernment(27, "Dictatorship"));
            Governments.Add(new FormOfGovernment(28, "Feudalism"));
            Governments.Add(new FormOfGovernment(29, "Feudalism"));
            Governments.Add(new FormOfGovernment(30, "Feudalism"));
            Governments.Add(new FormOfGovernment(31, "Feudalism"));
            Governments.Add(new FormOfGovernment(32, "Feudalism"));
            Governments.Add(new FormOfGovernment(33, "Feudalism"));
            Governments.Add(new FormOfGovernment(34, "Feudalism"));
            Governments.Add(new FormOfGovernment(35, "Feudalism"));
            Governments.Add(new FormOfGovernment(36, "Feudalism"));
            Governments.Add(new FormOfGovernment(37, "Feudalism"));
            Governments.Add(new FormOfGovernment(38, "Feudalism"));
            Governments.Add(new FormOfGovernment(39, "Feudalism"));
            Governments.Add(new FormOfGovernment(40, "Feudalism"));
            Governments.Add(new FormOfGovernment(41, "Feudalism"));
            Governments.Add(new FormOfGovernment(42, "Feudalism"));
            Governments.Add(new FormOfGovernment(43, "Gerontocracy"));
            Governments.Add(new FormOfGovernment(44, "Gerontocracy"));
            Governments.Add(new FormOfGovernment(45, "Hierarchy"));
            Governments.Add(new FormOfGovernment(46, "Hierarchy"));
            Governments.Add(new FormOfGovernment(47, "Hierarchy"));
            Governments.Add(new FormOfGovernment(48, "Hierarchy"));
            Governments.Add(new FormOfGovernment(49, "Hierarchy"));
            Governments.Add(new FormOfGovernment(50, "Hierarchy"));
            Governments.Add(new FormOfGovernment(51, "Hierarchy"));
            Governments.Add(new FormOfGovernment(52, "Hierarchy"));
            Governments.Add(new FormOfGovernment(53, "Hierarchy"));
            Governments.Add(new FormOfGovernment(54, "Magocracy"));
            Governments.Add(new FormOfGovernment(55, "Magocracy"));
            Governments.Add(new FormOfGovernment(56, "Magocracy"));
            Governments.Add(new FormOfGovernment(57, "Matriarchy"));
            Governments.Add(new FormOfGovernment(58, "Matriarchy"));
            Governments.Add(new FormOfGovernment(59, "Militocracy"));
            Governments.Add(new FormOfGovernment(60, "Militocracy"));
            Governments.Add(new FormOfGovernment(61, "Militocracy"));
            Governments.Add(new FormOfGovernment(62, "Militocracy"));
            Governments.Add(new FormOfGovernment(63, "Militocracy"));
            Governments.Add(new FormOfGovernment(64, "Militocracy"));
            Governments.Add(new FormOfGovernment(65, "Monarchy"));
            Governments.Add(new FormOfGovernment(66, "Monarchy"));
            Governments.Add(new FormOfGovernment(67, "Monarchy"));
            Governments.Add(new FormOfGovernment(68, "Monarchy"));
            Governments.Add(new FormOfGovernment(69, "Monarchy"));
            Governments.Add(new FormOfGovernment(70, "Monarchy"));
            Governments.Add(new FormOfGovernment(71, "Monarchy"));
            Governments.Add(new FormOfGovernment(72, "Monarchy"));
            Governments.Add(new FormOfGovernment(73, "Monarchy"));
            Governments.Add(new FormOfGovernment(74, "Monarchy"));
            Governments.Add(new FormOfGovernment(75, "Oligarchy"));
            Governments.Add(new FormOfGovernment(76, "Oligarchy"));
            Governments.Add(new FormOfGovernment(77, "Oligarchy"));
            Governments.Add(new FormOfGovernment(78, "Oligarchy"));
            Governments.Add(new FormOfGovernment(79, "Patriarchy"));
            Governments.Add(new FormOfGovernment(80, "Patriarchy"));
            Governments.Add(new FormOfGovernment(81, "Meritocracy"));
            Governments.Add(new FormOfGovernment(82, "Meritocracy"));
            Governments.Add(new FormOfGovernment(83, "Meritocracy"));
            Governments.Add(new FormOfGovernment(84, "Plutocracy"));
            Governments.Add(new FormOfGovernment(85, "Plutocracy"));
            Governments.Add(new FormOfGovernment(86, "Republic"));
            Governments.Add(new FormOfGovernment(87, "Republic"));
            Governments.Add(new FormOfGovernment(88, "Republic"));
            Governments.Add(new FormOfGovernment(89, "Republic"));
            Governments.Add(new FormOfGovernment(90, "Republic"));
            Governments.Add(new FormOfGovernment(91, "Republic"));
            Governments.Add(new FormOfGovernment(92, "Republic"));
            Governments.Add(new FormOfGovernment(93, "Satarpy"));
            Governments.Add(new FormOfGovernment(94, "Satarpy"));
            Governments.Add(new FormOfGovernment(95, "Kleptocracy"));
            Governments.Add(new FormOfGovernment(96, "Theocracy"));
            Governments.Add(new FormOfGovernment(97, "Theocracy"));
            Governments.Add(new FormOfGovernment(98, "Theocracy"));
            Governments.Add(new FormOfGovernment(99, "Theocracy"));
            Governments.Add(new FormOfGovernment(100, "Theocracy"));
        }
    }
}
