namespace RandomTables.Book1
{
    public class MaleNames1
    {
        public static Dictionary<int, string> maleNames = new();
        
        static MaleNames1()
        {
            maleNames = new Dictionary<int, string>
            {
                { 1, "Willoughby" },
                { 2, "Ryley" },
                { 3, "Ryle" },
                { 4, "Teddie" },
                { 5, "York" },
                { 6, "Stroud" },
                { 7, "Redford" },
                { 8, "Erwin" },
                { 9, "Burley" },
                { 10, "Manning" },
                { 11, "Frayne" },
                { 12, "Lyndell" },
                { 13, "Barton" },
                { 14, "Chadwick" },
                { 15, "Radcliff" },
                { 16, "Rufford" },
                { 17, "Waite" },
                { 18, "Saunderson" },
                { 19, "Prescott" },
                { 20, "Pollock" },
                { 21, "Aldwyn" },
                { 22, "Marlow" },
                { 23, "Huntley" },
                { 24, "Locke" },
                { 25, "Oxford" },
                { 26, "Ryle" },
                { 27, "Ryle" },
                { 28, "Ryle" },
                { 29, "Ryle" },
                { 30, "Ryle" },
                { 31, "Ryle" },
                { 32, "Ryle" },
                { 33, "Ryle" },
                { 34, "Ryle" },
                { 35, "Ryle" },
                { 36, "Ryle" },
                { 37, "Ryle" },
                { 38, "Ryle" },
                { 39, "Ryle" },
                { 40, "Ryle" },
                { 41, "Ryle" },
                { 42, "Ryle" },
                { 43, "Ryle" },
                { 44, "Ryle" },
                { 45, "Ryle" },
                { 46, "Ryle" },
                { 47, "Ryle" },
                { 48, "Ryle" },
                { 49, "Ryle" },
                { 50, "Ryle" },
                { 51, "Ryle" },
                { 52, "Ryle" },
                { 53, "Ryle" },
                { 54, "Ryle" },
                { 55, "Ryle" },
                { 56, "Ryle" },
                { 57, "Ryle" },
                { 58, "Ryle" },
                { 59, "Ryle" },
                { 60, "Ryle" },
                { 61, "Ryle" },
                { 62, "Ryle" },
                { 63, "Ryle" },
                { 64, "Ryle" },
                { 65, "Ryle" },
                { 66, "Ryle" },
                { 67, "Ryle" },
                { 68, "Ryle" },
                { 69, "Ryle" },
                { 70, "Ryle" },
                { 71, "Ryle" },
                { 72, "Ryle" },
                { 73, "Ryle" },
                { 74, "Ryle" },
                { 75, "Ryle" },
                { 76, "Ryle" },
                { 77, "Ryle" },
                { 78, "Ryle" },
                { 79, "Ryle" },
                { 80, "Ryle" },
                { 81, "Ryle" },
                { 82, "Ryle" },
                { 83, "Ryle" },
                { 84, "Ryle" },
                { 85, "Ryle" },
                { 86, "Ryle" },
                { 87, "Ryle" },
                { 88, "Ryle" },
                { 89, "Ryle" },
                { 90, "Ryle" },
                { 91, "Ryle" },
                { 92, "Ryle" },
                { 93, "Ryle" },
                { 94, "Ryle" },
                { 95, "Ryle" },
                { 96, "Ryle" },
                { 97, "Ryle" },
                { 98, "Ryle" },
                { 99, "Ryle" },
                { 100, "Ryle" }
            };
        }
    }
}
